# ASGARD Stripe Configuration Script
# This script helps configure Stripe API keys for ASGARD

param(
    [Parameter(Mandatory=$true)]
    [string]$StripeSecretKey,
    
    [Parameter(Mandatory=$false)]
    [string]$WebhookSecret = "",
    
    [Parameter(Mandatory=$false)]
    [string]$SuccessURL = "http://localhost:5173/dashboard?success=true",
    
    [Parameter(Mandatory=$false)]
    [string]$CancelURL = "http://localhost:5173/pricing",
    
    [Parameter(Mandatory=$false)]
    [string]$PortalReturnURL = "http://localhost:5173/dashboard"
)

Write-Host "=== ASGARD Stripe Configuration ===" -ForegroundColor Cyan
Write-Host ""

# Validate Stripe key format
if (-not $StripeSecretKey.StartsWith("sk_live_") -and -not $StripeSecretKey.StartsWith("sk_test_")) {
    Write-Host "ERROR: Invalid Stripe secret key format. Should start with 'sk_live_' or 'sk_test_'" -ForegroundColor Red
    exit 1
}

# Check if .env file exists
$envPath = Join-Path $PSScriptRoot ".." ".env"
if (-not (Test-Path $envPath)) {
    Write-Host "Creating .env file from .env.example..." -ForegroundColor Yellow
    $examplePath = Join-Path $PSScriptRoot ".." ".env.example"
    if (Test-Path $examplePath) {
        Copy-Item $examplePath $envPath
    } else {
        # Create basic .env file
        @"
# ASGARD Environment Variables
# Generated by setup_stripe.ps1

# Stripe Configuration
STRIPE_SECRET_KEY=$StripeSecretKey
STRIPE_WEBHOOK_SECRET=$WebhookSecret
STRIPE_SUCCESS_URL=$SuccessURL
STRIPE_CANCEL_URL=$CancelURL
STRIPE_PORTAL_RETURN_URL=$PortalReturnURL
"@ | Out-File -FilePath $envPath -Encoding utf8
    }
} else {
    Write-Host "Updating existing .env file..." -ForegroundColor Yellow
}

# Update .env file with Stripe configuration
$envContent = Get-Content $envPath -Raw

# Update or add Stripe variables
$vars = @{
    "STRIPE_SECRET_KEY" = $StripeSecretKey
    "STRIPE_WEBHOOK_SECRET" = $WebhookSecret
    "STRIPE_SUCCESS_URL" = $SuccessURL
    "STRIPE_CANCEL_URL" = $CancelURL
    "STRIPE_PORTAL_RETURN_URL" = $PortalReturnURL
}

foreach ($key in $vars.Keys) {
    $value = $vars[$key]
    $pattern = "^\s*$key\s*=.*$"
    $replacement = "$key=$value"
    
    if ($envContent -match $pattern) {
        $envContent = $envContent -replace $pattern, $replacement
        Write-Host "Updated $key" -ForegroundColor Green
    } else {
        # Add new variable
        if (-not $envContent.EndsWith("`n")) {
            $envContent += "`n"
        }
        $envContent += "$replacement`n"
        Write-Host "Added $key" -ForegroundColor Green
    }
}

# Save updated .env file
$envContent | Out-File -FilePath $envPath -Encoding utf8 -NoNewline

Write-Host ""
Write-Host "✓ Stripe configuration saved to .env" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Set up Stripe Price IDs in internal/services/stripe.go" -ForegroundColor White
Write-Host "2. Configure webhook endpoint in Stripe Dashboard" -ForegroundColor White
Write-Host "3. Copy webhook secret to STRIPE_WEBHOOK_SECRET" -ForegroundColor White
Write-Host "4. Restart your application to load the new configuration" -ForegroundColor White
Write-Host ""
Write-Host "For webhook setup:" -ForegroundColor Cyan
Write-Host "  - Endpoint URL: https://aura-genesis.org/api/webhooks/stripe" -ForegroundColor White
Write-Host "  - Events: checkout.session.completed, customer.subscription.*, invoice.payment.*" -ForegroundColor White
Write-Host ""
